when@dev:
    web_profiler:
        toolbar: false  # Désactiver la barre d'outils
        intercept_redirects: false

    framework:
        profiler:
            only_exceptions: true  # Collecter les données uniquement pour les exceptions
            collect: false  # Désactiver la collecte des données

when@test:
    web_profiler:
        toolbar: false
        intercept_redirects: false
    
    framework:
        profiler: 
            collect: false
            only_exceptions: true

when@prod:
    web_profiler:
        toolbar: false
        intercept_redirects: false
    framework:
        profiler:
            collect: false
